from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
RAW_CHEST_XRAY_DIR = RAW_DATA_DIR / "chest_xray"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
SPLIT_DIR = PROCESSED_DATA_DIR / "splits"
EXTERNAL_DATA_DIR = DATA_DIR / "external"

MODEL_DIR = PROJECT_ROOT / "models"
CHECKPOINT_DIR = MODEL_DIR / "checkpoints"
METRICS_DIR = MODEL_DIR / "metrics"

REPORTS_DIR = PROJECT_ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"
TABLES_DIR = REPORTS_DIR / "tables"

SEED = 42

IMAGE_SIZE = 224
BATCH_SIZE = 32
NUM_WORKERS = 4
VAL_FRACTION = 0.15
BASELINE_EPOCHS = 10
BASELINE_LR = 1e-3
WEIGHT_DECAY = 1e-4

IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

CLASS_NAMES = ("NORMAL", "PNEUMONIA")
LABEL_MAP = {"NORMAL": 0, "PNEUMONIA": 1}

TRAIN_DIRNAME = "train"
VAL_DIRNAME = "val"
TEST_DIRNAME = "test"

DEVICE = "cuda"
